### ISSUE TITLE
Wrong file in plasma guide.

### ISSUE THREAD

**Issue by ITCMD** [MycroftAI/installers#10]
Here: https://mycroft.ai/blog/mycroft-gets-a-plasmoid/

you have the link to the old file. The wget files should be on this repository. Here is the correct wget command: 
`wget https://raw.githubusercontent.com/MycroftAI/installers/master/kde_plasmoid_debian/install.sh`

**Comment by krisgesling** [comment]
Thanks for the heads up. 

I've updated the vanity links so they redirect to the appropriate scripts properly. So this should now be updated :)
